---
- name: Generate and Install the configuration on JUNOS Devices
  hosts: all
  roles:
       - juniper.junos
  connection: local
  gather_facts: no

  vars: 
    tmp_dir: "tmp"
    conf_file: "{{tmp_dir}}/{{inventory_hostname}}.conf"

  tasks:
    - debug: var=tmp_dir

    - debug: var=conf_file

    - name: Create configs directory
      file:
         path: "{{ tmp_dir }}"
         state: directory

    - name: Save device information using Templates
      template:
         src: templates/VJ.j2
         dest: "{{ conf_file }}"
 







 
