---
- name: My first ansible program to provison VRF on JUNOS
  hosts: VJ1 
  gather_facts: false
  tasks:
  - name: Configure VRF_2
    junos_config:
      lines:
           - set routing-instances VRF_2 instance-type vrf
           - set routing-instances VRF_2 interface lo0.2
           - set routing-instances VRF_2 route-distinguisher 100.0.0.1:2
           - set routing-instances VRF_2 vrf-target target:9583:2
           - set interfaces lo0 unit 2 family inet address 101.0.0.1/32











