---
- name: Template for VJ configuration
  hosts: localhost
  tasks:
  - name: Loopback Address Template
    template:
      src: VJ.j2
      dest: "VJ_configs/{{item.router}}.txt"
    with_items:
              - {router: VJ1, loopback: 0, host: 1}
              - {router: VJ2, loopback: 0, host: 2}
              - {router: VJ3, loopback: 0, host: 3}



